### ISSUE TITLE
[ISSUE] Subsequent plan has changes?

### ISSUE THREAD

**Issue by roy-work** [databrickslabs/terraform-provider-databricks#782] opened 2021-08-18 20:31 UTC
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
```
Terraform v0.15.5
```

`0.3.2` of the databricks provider. (<s>I'm going to try upgrading this, as I see it is not the most recent.</s> It seems like other bugs in the provider prevent upgrading. I'll see about filing a separate issue for that. (Done: #783))

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_cluster
- databricks_instance_pool

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Environment variable names
To get relevant environment variable _names_ please copypaste the output of the following command:
`$ env | sort | grep -E 'DATABRICKS|AWS|AZURE|ARM|TEST' | awk -F= '{print $1}'`

### Terraform Configuration Files
```hcl
resource "databricks_cluster" "databricks" {
  cluster_name            = "${local.prefix}-cluster"
  spark_version           = "8.1.x-scala2.12"
  node_type_id            = data.databricks_node_type.nodes.id
  autotermination_minutes = 60
  autoscale {
    min_workers = 3
    max_workers = 9
  }
  spark_env_vars = {
    "PYSPARK_PYTHON" = "/databricks/python3/bin/python3"
  }
  azure_attributes{
    first_on_demand = 1
    availability = "ON_DEMAND_AZURE"
    spot_bid_max_price = -1
  }
  spark_conf = {
    "spark.databricks.delta.preview.enabled" = "true"
  }

  library {
    pypi {
      package = "requests"
    }
  }

  library {
    pypi {
      package = "datadog"
    }
  }
}

resource "databricks_instance_pool" "databricks_streaming" {
  instance_pool_name = "streaming"
  min_idle_instances = 0
  max_capacity       = 6
  node_type_id       = data.databricks_node_type.nodes.id
  azure_attributes {
    availability = "ON_DEMAND"
  }
  idle_instance_autotermination_minutes = 60
  disk_spec {
    disk_type {
      ebs_volume_type = "GENERAL_PURPOSE_SSD"
    }
  }
}

resource "databricks_cluster" "databricks_kafkastreaming" {
  cluster_name            = "${local.prefix}-kafka-cluster"
  spark_version           = "8.1.x-scala2.12"
  instance_pool_id        = resource.databricks_instance_pool.databricks_streaming.id
  autotermination_minutes = 60
  autoscale {
    min_workers = 3
    max_workers = 9
  }
  spark_env_vars = {
    "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
  }
  azure_attributes{
    first_on_demand = 1
    availability = "ON_DEMAND_AZURE"
    spot_bid_max_price = -1
  }
  spark_conf = {
    "spark.databricks.delta.preview.enabled": "true"
  }
}
```

### Debug Output
Please add turn on logging, e.g. `TF_LOG=DEBUG terraform apply` and run command again, paste it to gist & provide the link to gist. If you're still willing to paste in log output, make sure you provide only relevant log lines with requests.

It would make it more readable, if you pipe the log through `| grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'`, e.g.:

```
TF_LOG=DEBUG terraform plan 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
After an apply, the subsequent plan should be clean, as nothing has changed in code, and nothing was changed in the actual infra.

### Actual Behavior
We get the following plan changes:
```
  # databricks_cluster.databricks will be updated in-place
  ~ resource "databricks_cluster" "databricks" {
        id                           = "[snip]"
      ~ node_type_id                 = "Standard_D3_v2" -> "Standard_DS3_v2"
        # (14 unchanged attributes hidden)



        # (4 unchanged blocks hidden)
    }

  # databricks_cluster.databricks_kafkastreaming will be updated in-place
  ~ resource "databricks_cluster" "databricks_kafkastreaming" {
        id                           = "[snip]"
      ~ instance_pool_id             = "[snip]" -> (known after apply)
        # (15 unchanged attributes hidden)


      ~ azure_attributes {
          ~ availability       = "SPOT_WITH_FALLBACK_AZURE" -> "ON_DEMAND_AZURE"
          ~ first_on_demand    = 2147483647 -> 1
            # (1 unchanged attribute hidden)
        }
        # (1 unchanged block hidden)
    }

  # databricks_instance_pool.databricks_streaming must be replaced
-/+ resource "databricks_instance_pool" "databricks_streaming" {
      ~ id                                    = "[snip]" -> (known after apply)
      ~ instance_pool_id                      = "[snip]" -> (known after apply)
      ~ node_type_id                          = "Standard_D3_v2" -> "Standard_DS3_v2" # forces replacement
        # (5 unchanged attributes hidden)

      ~ azure_attributes {
          ~ availability       = "ON_DEMAND_AZURE" -> "ON_DEMAND" # forces replacement
          ~ spot_bid_max_price = 0 -> (known after apply)
        }

      ~ disk_spec {
          - disk_count = 0 -> null
          - disk_size  = 0 -> null

          ~ disk_type {
                # (1 unchanged attribute hidden)
            }
        }
    }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`

### Important Factoids
Are there anything atypical about your accounts that we should know? We are running on TFE.

**Comment by nfx** [comment] 2021-08-20 12:55
Duplicate of #748

**Closed by nfx** 2021-08-20 12:55 UTC
