### ISSUE TITLE
[ISSUE] Warnings or "Error: Response from server (429)" when applying notebooks

### ISSUE THREAD

**Issue by mikemowgli** [databrickslabs/terraform-provider-databricks#52] opened 2020-05-13 11:16 UTC
Hi there,

### Terraform Version
```
$ terraform version
Terraform v0.12.24
+ provider.azuread v0.8.0
+ provider.azurerm v2.5.0
+ provider.databricks v0.1.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_notebook

### Terraform Configuration Files
```hcl
resource "databricks_notebook" "tamers-databricks-nb-handson-unsupervised-02" {
  content   = filebase64("notebooks/handson-unsupervised-02-end-to-end-machine-learning-project.py")
  language  = "PYTHON"
  path      = "/Shared/xxxx/handson-unsupervised-02-end-to-end-machine-learning-project.py"
  overwrite = false
  mkdirs    = true
  format    = "SOURCE"
}
```

### Debug Output
https://gist.github.com/mikemowgli/42c32bd11e21d926cadc7b05788d49d7

### Expected Behavior
No error nor warning when applying

### Actual Behavior
warning or errors

### Steps to Reproduce
`TF_LOG=DEBUG terraform apply -target databricks_notebook.tamers-databricks-nb-handson-unsupervised-02`

### Important Factoids
In an Azure Databricks workspace, a terraform apply on a specific notebook (using `-target` option) yields the log in the gist link: only a warning, and the content of the notebook not updated but left as-is.
However, when applying all my terraform plan, I get the same debug log, with only this difference at the very end:
```
databricks_notebook.tamers-databricks-nb-handson-unsupervised-02: Creation complete after 3s [id=/Shared/xxxx/handson-unsupervised-02-end-to-end-machine-learning-project.py]

Error: Response from server (429)


2020-05-13T12:58:48.240+0200 [DEBUG] plugin: plugin process exited: path=/home/mvdborne/.terraform.d/plugins/linux_amd64/terraform-provider-databricks_v0.1.0 pid=8267
2020-05-13T12:58:48.240+0200 [DEBUG] plugin: plugin exited
$ echo $?
1
```

### References
I'm impacted by [the notebook content issue](https://github.com/databrickslabs/databricks-terraform/issues/42), so this one might be a consequence of issue 42.

**Comment by mikemowgli** [comment] 2020-05-13 11:39
Please note that I can mitigate the Error 429 with `terraform apply -parallelism=1` (value of -parallelism=2` gives the same error).
Though the warnings persists of course.

**Comment by stikkireddy** [comment] 2020-05-13 16:25
The delete apis will fail with a 429 when you try to concurrently delete files, I will try to get these changes in hopefully by tomorrow. thanks for identifying this :)

**Comment by mikemowgli** [comment] 2020-06-16 08:17
any news on this one?

**Comment by nfx** [comment] 2020-06-25 13:23
Closing this as duplicate of #111

**Closed by nfx** 2020-06-25 13:23 UTC
Labels: bug
