### ISSUE TITLE
[ISSUE] Provider issue - cluster state refresh operation hangs and causes deployment to fail after switching to new provider version 0.4.0

### ISSUE THREAD

**Issue by nischays** [databrickslabs/terraform-provider-databricks#960] opened 2021-12-13 23:05 UTC
### Terraform Configuration Files
```
data "databricks_spark_version" "latest_lts" {
  long_term_support = true
}

resource "databricks_cluster" "single_node_cluster" {
  cluster_name            = "Single Node Cluster"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = "Standard_DS3_v2"
  autotermination_minutes = 20
  policy_id               = databricks_cluster_policy.external_hive_metastore_policy.id

  ### insert spark config here

  custom_tags = {
    "ResourceClass" = "SingleNode"
  }

  dynamic "library" {
    for_each = var.pypi_libraries
    content {
      pypi {
        package = library.value
      }
    }
  }
}
```

### Expected Behavior
Cluster state refresh operation should have succeeded.

### Actual Behavior
Cluster state refresh operation hangs with error message:
##[debug]Error: cannot read cluster: 0 libraries are ready, but there are still 4 pending

### Steps to Reproduce
1. deploy a databricks cluster using provider version 0.3.9 and config provided above
2. terraform apply
3. Update the provider to 0.4.0
4. terraform plan
5. Deployment will hang

### Terraform and provider versions

terraform version: 1.0.0
databricks provider: v0.4.0

**Comment by nfx** [comment] 2021-12-14 00:06
Duplicate of #952

**Closed** 2021-12-14 00:07 UTC
