### ISSUE TITLE
[ISSUE] databricks_permissions complains about workspace_id 

### ISSUE THREAD

**Issue by KoenR3** [databrickslabs/terraform-provider-databricks#778] opened 2021-08-17 10:03 UTC
### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_permissions

### Debug Output
Because of confidential info in the apply, I cannot give the full debug output

### Expected Behavior
Applying a permission for tokens should create the permission (everything worked in 0.3.6)

### Actual Behavior
Complains about the workspace ID missing (seems to be it wants to have the provider initialization in another way?)
```
 Error: INVALID_PARAMETER_VALUE: Missing required field: workspace_id
│ 
│   with module.tokens.databricks_permissions.token_usage,
│   on ../../modules/tokens/acl-tokens.tf line 1, in resource "databricks_permissions" "token_usage":
│    1: resource "databricks_permissions" "token_usage" {

```

### Steps to Reproduce
Grant permissions on tokens, as an example

```
resource "databricks_permissions" "token_usage" {

  authorization = "tokens"

  dynamic "access_control" {
    for_each = { for group_key, group in var.usergroups : group_key => group if group.allow_tokens }
    content {
      group_name       = access_control.value.display_name
      permission_level = "CAN_USE"
    }
  }

  dynamic "access_control" {
    for_each = var.service_principals
    content {
      service_principal_name = access_control.value.application_id
      permission_level       = "CAN_USE"
    }

  }

}
```

**Comment by KoenR3** [comment] 2021-08-17 10:08
It seems the issue now persists on all resources no matter which version of the provider I use, even after reverting the code changes.  I will close this and investigate further...

**Comment by KoenR3** [comment] 2021-08-17 10:42
I will have to reopen this as I cannot find a root cause anymore.  Any apply on databricks_permissions for tokens now gives a `INVALID_PARAMETER_VALUE: Missing required field: workspace_id`

**Comment by rinzool** [comment] 2021-08-17 15:39
:information_source: I have the same issue. I noticed that it does *not* appear for passwords (with `authorization = "passwords"`)

**Comment by vnourdin** [comment] 2021-08-18 07:04
Same issue in our projects too !

**Comment by KoenR3** [comment] 2021-08-19 11:15
@rinzool What did you do to fix it?

**Comment by KoenR3** [comment] 2021-08-19 19:13
The issue seems to have resolved.  Was it an issue on the platform side?  @vnourdin could you check if it works on your projects?

**Comment by rinzool** [comment] 2021-08-19 19:16
I did nothing I resolved itself. @vnourdin confirm it to me too

**Comment by nfx** [comment] 2021-08-20 08:13
@vnourdin @KoenR3 @rinzool I'm checking with IAM team now

**Comment by nfx** [comment] 2021-08-20 12:55
Closing this issue for now, as it seems to be fixed now. Please reopen it if re-occurs

**Closed by nfx** 2021-08-20 12:55 UTC
Labels: invalid

**Comment by nfx** [comment] 2021-08-20 17:11
And I can confirm it is just a glitch.
