### ISSUE TITLE
[ISSUE] Separate resource for libraries of a cluster?

### ISSUE THREAD

**Issue by itachiRedhair** [databrickslabs/terraform-provider-databricks#468] opened 2021-01-25 15:28 UTC
Currently, libraries are being managed as a part of cluster resources. Because of this whenever there is a change in the cluster, if libraries are not defined in the terraform configuration for the cluster, existing libraries (the ones which are added without terraform) get uninstalled.
If we can have a library as a separate resource it will be possible to have an option to manage libraries outside or as a part of Terraform configuration.

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_cluster

### Expected Behavior
Libraries of a cluster should be allowed to manage outside terraform configuration.

### Actual Behavior
Libraries getting uninstalled when terraform modifies the databricks_cluster resource.

**Comment by nfx** [comment] 2021-01-25 15:45
Hi @itachiRedhair `databricks_cluster` resource works as designed at the moment and feature is already used this way by all customers. 

If you would like to take on creating `databricks_cluster_library` resource with 95% code coverage, integration tests, documentation, and making sure it doesn't conflict with `databricks_cluster` installed library - please indicate :) happy to accept PR.

**Comment by itachiRedhair** [comment] 2021-01-25 16:50
@nfx I will check how I can contribute towards `databricks_cluster_library` resource. 

I have one question, is it possible to somehow skip library install/uninstall for the `databricks_cluster` resource?

If I understood this function correctly https://github.com/databrickslabs/terraform-provider-databricks/blob/732b3f01224658d9ee01a594f3be1e5d27a613f8/compute/resource_cluster.go#L229

it will find the difference between installed libraries and libraries defined in terraform configuration and take action based on it. This means that on every cluster update (doesn't matter what's forcing the update) if there is a mismatch in defined and installed libraries, it will install/uninstall them. But the thing which could be bothering the user is that libraries which are getting uninstalled is not coming up in the plan.

**Comment by nfx** [comment] 2021-01-25 22:23
Hm. Libraries getting uninstalled can be fixed. Please describe how you reproduce it

**Comment by nfx** [comment] 2021-01-25 22:26
My goal is to keep already bloated cluster resource simple as much as possible, because it’s the most important part of the codebase. Getting if-conditions in library checking code might be too risky in the long term perspective. 

Getting uninstalling libraries not to affect the plan is simpler. Please create a new issue for it and ill close this one.

**Comment by nfx** [comment] 2021-11-10 20:29
Closing in favour of #904

**Closed by nfx** 2021-11-10 20:29 UTC
