### ISSUE TITLE
[ISSUE] Broken install script: missing databricks-terraform_0.2.2_Linux_64-bit.tar.gz

### ISSUE THREAD

**Issue by algattik** [databrickslabs/terraform-provider-databricks#123] opened 2020-06-19 06:57 UTC
2020-06-19T06:52:09.4868005Z ##[group]Run curl https://raw.githubusercontent.com/databrickslabs/databricks-terraform/master/godownloader-databricks-provider.sh | bash -xs -- -b $HOME/.terraform.d/plugins
2020-06-19T06:52:09.4868582Z [36;1mcurl https://raw.githubusercontent.com/databrickslabs/databricks-terraform/master/godownloader-databricks-provider.sh | bash -xs -- -b $HOME/.terraform.d/plugins[0m
2020-06-19T06:52:09.4889506Z shell: /bin/bash -e {0}
2020-06-19T06:52:09.5075836Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2020-06-19T06:52:09.5078203Z                                  Dload  Upload   Total   Spent    Left  Speed
2020-06-19T06:52:09.5078690Z 
2020-06-19T06:52:09.7197578Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2020-06-19T06:52:09.7198914Z 100  9892  100  9892    + set -e
2020-06-19T06:52:09.7200117Z 0     0  46881      0 --:--:-- --:--:-- --:--:-- 46881
2020-06-19T06:52:09.7237519Z + cat /dev/null
2020-06-19T06:52:09.7262696Z + _logp=6
2020-06-19T06:52:09.7303323Z + cat /dev/null
2020-06-19T06:52:09.7315227Z + PROJECT_NAME=databricks-terraform
2020-06-19T06:52:09.7315828Z + OWNER=databrickslabs
2020-06-19T06:52:09.7316504Z + REPO=databricks-terraform
2020-06-19T06:52:09.7317137Z + BINARY=terraform-provider-databricks_
2020-06-19T06:52:09.7317450Z + FORMAT=tar.gz
2020-06-19T06:52:09.7320080Z ++ uname_os
2020-06-19T06:52:09.7328195Z +++ uname -s
2020-06-19T06:52:09.7328887Z +++ tr '[:upper:]' '[:lower:]'
2020-06-19T06:52:09.7339749Z ++ os=linux
2020-06-19T06:52:09.7340090Z ++ case "$os" in
2020-06-19T06:52:09.7340343Z ++ echo linux
2020-06-19T06:52:09.7342199Z + OS=linux
2020-06-19T06:52:09.7345730Z ++ uname_arch
2020-06-19T06:52:09.7349705Z +++ uname -m
2020-06-19T06:52:09.7361827Z ++ arch=x86_64
2020-06-19T06:52:09.7362172Z ++ case $arch in
2020-06-19T06:52:09.7362456Z ++ arch=amd64
2020-06-19T06:52:09.7362714Z ++ echo amd64
2020-06-19T06:52:09.7364810Z + ARCH=amd64
2020-06-19T06:52:09.7366636Z + PREFIX=databrickslabs/databricks-terraform
2020-06-19T06:52:09.7367103Z + PLATFORM=linux/amd64
2020-06-19T06:52:09.7367928Z + GITHUB_DOWNLOAD=https://github.com/databrickslabs/databricks-terraform/releases/download
2020-06-19T06:52:09.7368330Z + uname_os_check linux
2020-06-19T06:52:09.7371055Z ++ uname_os
2020-06-19T06:52:09.7377484Z +++ uname -s
2020-06-19T06:52:09.7378259Z +++ tr '[:upper:]' '[:lower:]'
2020-06-19T06:52:09.7389977Z ++ os=linux
2020-06-19T06:52:09.7390276Z ++ case "$os" in
2020-06-19T06:52:09.7390549Z ++ echo linux
2020-06-19T06:52:09.7392657Z + os=linux
2020-06-19T06:52:09.7392994Z + case "$os" in
2020-06-19T06:52:09.7393247Z + return 0
2020-06-19T06:52:09.7394883Z + uname_arch_check amd64
2020-06-19T06:52:09.7396728Z ++ uname_arch
2020-06-19T06:52:09.7400686Z +++ uname -m
2020-06-19T06:52:09.7412571Z ++ arch=x86_64
2020-06-19T06:52:09.7413144Z ++ case $arch in
2020-06-19T06:52:09.7413466Z ++ arch=amd64
2020-06-19T06:52:09.7413760Z ++ echo amd64
2020-06-19T06:52:09.7415559Z + arch=amd64
2020-06-19T06:52:09.7415896Z + case "$arch" in
2020-06-19T06:52:09.7416217Z + return 0
2020-06-19T06:52:09.7417162Z + parse_args -b /home/algattik/.terraform.d/plugins
2020-06-19T06:52:09.7417490Z + BINDIR=./bin
2020-06-19T06:52:09.7418144Z + getopts 'b:dh?x' arg
2020-06-19T06:52:09.7418447Z + case "$arg" in
2020-06-19T06:52:09.7418779Z + BINDIR=/home/algattik/.terraform.d/plugins
2020-06-19T06:52:09.7419379Z + getopts 'b:dh?x' arg
2020-06-19T06:52:09.7420206Z + shift 2
2020-06-19T06:52:09.7420474Z + TAG=
2020-06-19T06:52:09.7420982Z + tag_to_version
2020-06-19T06:52:09.7421545Z + '[' -z '' ']'
2020-06-19T06:52:09.7422064Z + log_info 'checking GitHub for latest tag'
2020-06-19T06:52:09.7422406Z + log_priority 6
2020-06-19T06:52:09.7422759Z + test -z 6
2020-06-19T06:52:09.7423108Z + '[' 6 -le 6 ']'
2020-06-19T06:52:09.7423306Z ++ log_prefix
2020-06-19T06:52:09.7423679Z ++ echo databrickslabs/databricks-terraform
2020-06-19T06:52:09.7428905Z ++ log_tag 6
2020-06-19T06:52:09.7429234Z ++ case $1 in
2020-06-19T06:52:09.7429515Z ++ echo info
2020-06-19T06:52:09.7432063Z + echoerr databrickslabs/databricks-terraform info 'checking GitHub for latest tag'
2020-06-19T06:52:09.7432900Z + echo databrickslabs/databricks-terraform info 'checking GitHub for latest tag'
2020-06-19T06:52:09.7433392Z databrickslabs/databricks-terraform info checking GitHub for latest tag
2020-06-19T06:52:09.7435857Z ++ github_release databrickslabs/databricks-terraform ''
2020-06-19T06:52:09.7436543Z ++ owner_repo=databrickslabs/databricks-terraform
2020-06-19T06:52:09.7436862Z ++ version=
2020-06-19T06:52:09.7437284Z ++ test -z ''
2020-06-19T06:52:09.7437578Z ++ version=latest
2020-06-19T06:52:09.7438308Z ++ giturl=https://github.com/databrickslabs/databricks-terraform/releases/latest
2020-06-19T06:52:09.7441350Z +++ http_copy https://github.com/databrickslabs/databricks-terraform/releases/latest Accept:application/json
2020-06-19T06:52:09.7444896Z ++++ mktemp
2020-06-19T06:52:09.7457081Z +++ tmp=/tmp/tmp.tt0cQngulI
2020-06-19T06:52:09.7458457Z +++ http_download /tmp/tmp.tt0cQngulI https://github.com/databrickslabs/databricks-terraform/releases/latest Accept:application/json
2020-06-19T06:52:09.7459157Z +++ log_debug 'http_download https://github.com/databrickslabs/databricks-terraform/releases/latest'
2020-06-19T06:52:09.7459542Z +++ log_priority 7
2020-06-19T06:52:09.7460185Z +++ test -z 7
2020-06-19T06:52:09.7460707Z +++ '[' 7 -le 6 ']'
2020-06-19T06:52:09.7460977Z +++ return 0
2020-06-19T06:52:09.7461173Z +++ is_command curl
2020-06-19T06:52:09.7461517Z +++ command -v curl
2020-06-19T06:52:09.7462059Z +++ http_download_curl /tmp/tmp.tt0cQngulI https://github.com/databrickslabs/databricks-terraform/releases/latest Accept:application/json
2020-06-19T06:52:09.7462311Z +++ local_file=/tmp/tmp.tt0cQngulI
2020-06-19T06:52:09.7463079Z +++ source_url=https://github.com/databrickslabs/databricks-terraform/releases/latest
2020-06-19T06:52:09.7463327Z +++ header=Accept:application/json
2020-06-19T06:52:09.7463908Z +++ '[' -z Accept:application/json ']'
2020-06-19T06:52:09.7464721Z ++++ curl -w '%{http_code}' -sL -H Accept:application/json -o /tmp/tmp.tt0cQngulI https://github.com/databrickslabs/databricks-terraform/releases/latest
2020-06-19T06:52:10.5783972Z +++ code=200
2020-06-19T06:52:10.5785794Z +++ '[' 200 '!=' 200 ']'
2020-06-19T06:52:10.5786330Z +++ return 0
2020-06-19T06:52:10.5786888Z +++ return
2020-06-19T06:52:10.5791187Z ++++ cat /tmp/tmp.tt0cQngulI
2020-06-19T06:52:10.5806176Z +++ body='{"id":27709752,"tag_name":"v0.2.2","update_url":"/databrickslabs/terraform-provider-databricks/releases/tag/v0.2.2","update_authenticity_token":"pmj5q+iWTOWDunm7nPF6KcJz5Zw/rBKfl7+mRvfvfhE05mGw9dXT9gD3mbGO9uakP+3MZB0L0dWfWTtlJV0exA==","delete_url":"/databrickslabs/terraform-provider-databricks/releases/tag/v0.2.2","delete_authenticity_token":"SLyz4RHi4Q9rPf5iJk8TtUIu2CCzu+ONEQG0ChDzJsmKRmRYzTp9FDtHoeliz4dETSCYVE3vtuuspgQgNkxS9A==","edit_url":"/databrickslabs/terraform-provider-databricks/releases/edit/v0.2.2"}'
2020-06-19T06:52:10.5806799Z +++ rm -f /tmp/tmp.tt0cQngulI
2020-06-19T06:52:10.5817137Z +++ echo '{"id":27709752,"tag_name":"v0.2.2","update_url":"/databrickslabs/terraform-provider-databricks/releases/tag/v0.2.2","update_authenticity_token":"pmj5q+iWTOWDunm7nPF6KcJz5Zw/rBKfl7+mRvfvfhE05mGw9dXT9gD3mbGO9uakP+3MZB0L0dWfWTtlJV0exA==","delete_url":"/databrickslabs/terraform-provider-databricks/releases/tag/v0.2.2","delete_authenticity_token":"SLyz4RHi4Q9rPf5iJk8TtUIu2CCzu+ONEQG0ChDzJsmKRmRYzTp9FDtHoeliz4dETSCYVE3vtuuspgQgNkxS9A==","edit_url":"/databrickslabs/terraform-provider-databricks/releases/edit/v0.2.2"}'
2020-06-19T06:52:10.5819609Z ++ json='{"id":27709752,"tag_name":"v0.2.2","update_url":"/databrickslabs/terraform-provider-databricks/releases/tag/v0.2.2","update_authenticity_token":"pmj5q+iWTOWDunm7nPF6KcJz5Zw/rBKfl7+mRvfvfhE05mGw9dXT9gD3mbGO9uakP+3MZB0L0dWfWTtlJV0exA==","delete_url":"/databrickslabs/terraform-provider-databricks/releases/tag/v0.2.2","delete_authenticity_token":"SLyz4RHi4Q9rPf5iJk8TtUIu2CCzu+ONEQG0ChDzJsmKRmRYzTp9FDtHoeliz4dETSCYVE3vtuuspgQgNkxS9A==","edit_url":"/databrickslabs/terraform-provider-databricks/releases/edit/v0.2.2"}'
2020-06-19T06:52:10.5821057Z ++ test -z '{"id":27709752,"tag_name":"v0.2.2","update_url":"/databrickslabs/terraform-provider-databricks/releases/tag/v0.2.2","update_authenticity_token":"pmj5q+iWTOWDunm7nPF6KcJz5Zw/rBKfl7+mRvfvfhE05mGw9dXT9gD3mbGO9uakP+3MZB0L0dWfWTtlJV0exA==","delete_url":"/databrickslabs/terraform-provider-databricks/releases/tag/v0.2.2","delete_authenticity_token":"SLyz4RHi4Q9rPf5iJk8TtUIu2CCzu+ONEQG0ChDzJsmKRmRYzTp9FDtHoeliz4dETSCYVE3vtuuspgQgNkxS9A==","edit_url":"/databrickslabs/terraform-provider-databricks/releases/edit/v0.2.2"}'
2020-06-19T06:52:10.5829627Z +++ echo '{"id":27709752,"tag_name":"v0.2.2","update_url":"/databrickslabs/terraform-provider-databricks/releases/tag/v0.2.2","update_authenticity_token":"pmj5q+iWTOWDunm7nPF6KcJz5Zw/rBKfl7+mRvfvfhE05mGw9dXT9gD3mbGO9uakP+3MZB0L0dWfWTtlJV0exA==","delete_url":"/databrickslabs/terraform-provider-databricks/releases/tag/v0.2.2","delete_authenticity_token":"SLyz4RHi4Q9rPf5iJk8TtUIu2CCzu+ONEQG0ChDzJsmKRmRYzTp9FDtHoeliz4dETSCYVE3vtuuspgQgNkxS9A==","edit_url":"/databrickslabs/terraform-provider-databricks/releases/edit/v0.2.2"}'
2020-06-19T06:52:10.5830388Z +++ tr -s '\n' ' '
2020-06-19T06:52:10.5830812Z +++ sed 's/.*"tag_name":"//'
2020-06-19T06:52:10.5834565Z +++ sed 's/".*//'
2020-06-19T06:52:10.5850668Z ++ version=v0.2.2
2020-06-19T06:52:10.5851592Z ++ test -z v0.2.2
2020-06-19T06:52:10.5851796Z ++ echo v0.2.2
2020-06-19T06:52:10.5853338Z + REALTAG=v0.2.2
2020-06-19T06:52:10.5853669Z + true
2020-06-19T06:52:10.5854274Z + test -z v0.2.2
2020-06-19T06:52:10.5854565Z + TAG=v0.2.2
2020-06-19T06:52:10.5854847Z + VERSION=0.2.2
2020-06-19T06:52:10.5855157Z + get_binaries
2020-06-19T06:52:10.5855433Z + case "$PLATFORM" in
2020-06-19T06:52:10.5856074Z + BINARIES=terraform-provider-databricks_v0.2.2
2020-06-19T06:52:10.5856376Z + adjust_format
2020-06-19T06:52:10.5856668Z + case ${OS} in
2020-06-19T06:52:10.5857065Z + true
2020-06-19T06:52:10.5857393Z + adjust_os
2020-06-19T06:52:10.5857667Z + case ${OS} in
2020-06-19T06:52:10.5857951Z + OS=Linux
2020-06-19T06:52:10.5858284Z + true
2020-06-19T06:52:10.5858521Z + adjust_arch
2020-06-19T06:52:10.5858720Z + case ${ARCH} in
2020-06-19T06:52:10.5859110Z + ARCH=64-bit
2020-06-19T06:52:10.5859297Z + true
2020-06-19T06:52:10.5859725Z + log_info 'found version: 0.2.2 for v0.2.2/Linux/64-bit'
2020-06-19T06:52:10.5859929Z + log_priority 6
2020-06-19T06:52:10.5860291Z + test -z 6
2020-06-19T06:52:10.5860777Z + '[' 6 -le 6 ']'
2020-06-19T06:52:10.5861150Z ++ log_prefix
2020-06-19T06:52:10.5861666Z ++ echo databrickslabs/databricks-terraform
2020-06-19T06:52:10.5867092Z ++ log_tag 6
2020-06-19T06:52:10.5867427Z ++ case $1 in
2020-06-19T06:52:10.5867728Z ++ echo info
2020-06-19T06:52:10.5871116Z + echoerr databrickslabs/databricks-terraform info 'found version: 0.2.2 for v0.2.2/Linux/64-bit'
2020-06-19T06:52:10.5871952Z + echo databrickslabs/databricks-terraform info 'found version: 0.2.2 for v0.2.2/Linux/64-bit'
2020-06-19T06:52:10.5872716Z databrickslabs/databricks-terraform info found version: 0.2.2 for v0.2.2/Linux/64-bit
2020-06-19T06:52:10.5873382Z + NAME=databricks-terraform_0.2.2_Linux_64-bit
2020-06-19T06:52:10.5873961Z + TARBALL=databricks-terraform_0.2.2_Linux_64-bit.tar.gz
2020-06-19T06:52:10.5874563Z + TARBALL_URL=https://github.com/databrickslabs/databricks-terraform/releases/download/v0.2.2/databricks-terraform_0.2.2_Linux_64-bit.tar.gz
2020-06-19T06:52:10.5874842Z + CHECKSUM=checksums.txt
2020-06-19T06:52:10.5875624Z + CHECKSUM_URL=https://github.com/databrickslabs/databricks-terraform/releases/download/v0.2.2/checksums.txt
2020-06-19T06:52:10.5876061Z + execute
2020-06-19T06:52:10.5876935Z ++ mktemp -d
2020-06-19T06:52:10.5884853Z + tmpdir=/tmp/tmp.AFs65PB3Su
2020-06-19T06:52:10.5885606Z + log_debug 'downloading files into /tmp/tmp.AFs65PB3Su'
2020-06-19T06:52:10.5885930Z + log_priority 7
2020-06-19T06:52:10.5886458Z + test -z 7
2020-06-19T06:52:10.5887020Z + '[' 7 -le 6 ']'
2020-06-19T06:52:10.5887303Z + return 0
2020-06-19T06:52:10.5888390Z + http_download /tmp/tmp.AFs65PB3Su/databricks-terraform_0.2.2_Linux_64-bit.tar.gz https://github.com/databrickslabs/databricks-terraform/releases/download/v0.2.2/databricks-terraform_0.2.2_Linux_64-bit.tar.gz
2020-06-19T06:52:10.5889315Z + log_debug 'http_download https://github.com/databrickslabs/databricks-terraform/releases/download/v0.2.2/databricks-terraform_0.2.2_Linux_64-bit.tar.gz'
2020-06-19T06:52:10.5889588Z + log_priority 7
2020-06-19T06:52:10.5889938Z + test -z 7
2020-06-19T06:52:10.5890294Z + '[' 7 -le 6 ']'
2020-06-19T06:52:10.5890501Z + return 0
2020-06-19T06:52:10.5890686Z + is_command curl
2020-06-19T06:52:10.5891105Z + command -v curl
2020-06-19T06:52:10.5891951Z + http_download_curl /tmp/tmp.AFs65PB3Su/databricks-terraform_0.2.2_Linux_64-bit.tar.gz https://github.com/databrickslabs/databricks-terraform/releases/download/v0.2.2/databricks-terraform_0.2.2_Linux_64-bit.tar.gz
2020-06-19T06:52:10.5892491Z + local_file=/tmp/tmp.AFs65PB3Su/databricks-terraform_0.2.2_Linux_64-bit.tar.gz
2020-06-19T06:52:10.5893207Z + source_url=https://github.com/databrickslabs/databricks-terraform/releases/download/v0.2.2/databricks-terraform_0.2.2_Linux_64-bit.tar.gz
2020-06-19T06:52:10.5893598Z + header=
2020-06-19T06:52:10.5893883Z + '[' -z '' ']'
2020-06-19T06:52:10.5894708Z ++ curl -w '%{http_code}' -sL -o /tmp/tmp.AFs65PB3Su/databricks-terraform_0.2.2_Linux_64-bit.tar.gz https://github.com/databrickslabs/databricks-terraform/releases/download/v0.2.2/databricks-terraform_0.2.2_Linux_64-bit.tar.gz
2020-06-19T06:52:10.9307320Z + code=404
2020-06-19T06:52:10.9309102Z + '[' 404 '!=' 200 ']'
2020-06-19T06:52:10.9310176Z + log_debug 'http_download_curl received HTTP status 404'
2020-06-19T06:52:10.9310740Z + log_priority 7
2020-06-19T06:52:10.9311672Z + test -z 7
2020-06-19T06:52:10.9312621Z + '[' 7 -le 6 ']'
2020-06-19T06:52:10.9313117Z + return 0
2020-06-19T06:52:10.9313627Z + return 1

**Comment by sdebruyn** [comment] 2020-06-19 08:19
Can confirm, got the same here: https://github.com/datarootsio/terraform-module-azure-datalake/runs/787241407

**Comment by stikkireddy** [comment] 2020-06-19 10:19
Hey thanks for catching this, I have a fix for this. Root cause is conforming to the requirements of this: https://registry.terraform.io/providers/databrickslabs/databricks/latest caused the godownloader generated script to fail. I have a fix for this will merge this in within the next hour or so. But on the bright side we are on the registry :) Community provider for now.

**Comment by stikkireddy** [comment] 2020-06-19 10:36
please verify that the script now works, it should be fixed.

**Comment by sdebruyn** [comment] 2020-06-19 12:12
I can confirm it's working again, thanks! 🙏 https://github.com/datarootsio/terraform-module-azure-datalake/runs/788001661

**Comment by algattik** [comment] 2020-06-19 13:24
Works! The script installs the provider.

**Comment by algattik** [comment] 2020-06-19 13:28
Script is failing though when trying to install older version.

```
curl https://raw.githubusercontent.com/databrickslabs/databricks-terraform/master/godownloader-databricks-provider.sh | bash -xs -- -b $HOME/.terraform.d/plugins v0.2.0
```

on Linux:

```
curl -w '%{http_code}' -sL -o /tmp/tmp.TPtfF6OdJE/terraform-provider-databricks_0.2.0_linux_amd64.zip https://github.com/databrickslabs/terraform-provider-databricks/releases/download/v0.2.0/terraform-provider-databricks_0.2.0_linux_amd64.zip
+ code=404
+ '[' 404 '!=' 200 ']'
+ log_debug 'http_download_curl received HTTP status 404'
```

On Mac:

```
curl -w '%{http_code}' -sL -o /var/folders/67/59_hhx6d5lz0wg__x35g8wbw0000gn/T/tmp.nbmnWiGw/terraform-provider-databricks_0.2.0_darwin_amd64.zip https://github.com/databrickslabs/terraform-provider-databricks/releases/download/v0.2.0/terraform-provider-databricks_0.2.0_darwin_amd64.zip
+ code=404
+ '[' 404 '!=' 200 ']'
+ log_debug 'http_download_curl received HTTP status 404'
```

**Comment by stikkireddy** [comment] 2020-06-19 17:22
unfortunately to conform to provider specs the script will not work with previous releases and they would need to be installed manually. Unfortunately the specs changed in the goreleaser file and naming conventions as well as checksum files :|. Still figuring out if there is a way re release old tags with the correct artifact names.

**Closed** 2020-06-22 22:38 UTC
Labels: bug
