### ISSUE TITLE
[FEATURE] Azure Key Vault-Backed Resource

### ISSUE THREAD

**Issue by RichardFowles89** [databrickslabs/terraform-provider-databricks#300] opened 2020-09-06 14:18 UTC
Hello, would it be possible to have a secret scope resource for Azure Key Vault-backed secret scopes? This would be extremely helpful as I would like to use the databricks_azure_adls_gen2_mount resource but need the secret scope to be Key Vault-backed.

### Terraform Configuration Files
EXAMPLE
```hcl
resource "databricks_azure_keyvault_secret_scope" "kv_secret_scope" {
    name                     = "application"
    initial_manage_principal = "users"
}

resource "databricks_azure_adls_gen2_mount" "dbx_datalake_mounts" {
    count                  = length(var.filesystems_to_mount)
    container_name         = data.azurerm_storage_container.filesystems[count.index].name
    storage_account_name   = data.azurerm_storage_account.datalake.name
    mount_name             = "my-mount"
    cluster_id             = databricks_cluster.cluster.id
    tenant_id              = data.azurerm_client_config.current.tenant_id
    client_id              = data.azurerm_client_config.current.client_id
    client_secret_scope    = databricks_secret_scope.kv_secret_scope.name
    client_secret_key      = databricks_secret.client_secret.key
    initialize_file_system = true
}
```

**Comment by nfx** [comment] 2020-09-06 15:40
@RichardFowles89 there’s no support for it on the backend side yet. Once it’s there - it will be in databricks_secret_scope, not in databricks_azure_keyvault_secret_scope.

This issue is a duplicate of earlier one.

**Closed by nfx** 2020-09-06 15:40 UTC
Labels: bug

**Comment by RichardFowles89** [comment] 2020-09-07 08:17
Great - @nfx thanks for letting me know.

**Comment by nfx** [comment] 2020-09-08 08:38
Duplicate of #49
