### ISSUE TITLE
while trying to run terraform code present in terraform-provider-Databricks unable to create workspace

### ISSUE THREAD

**Issue by karthik-koantek** [databrickslabs/terraform-provider-databricks#1363] opened 2022-06-07 15:42 UTC
HI Team,

we are using all modules present in workspace creation using above terraform-provider-Databricks, getting below error

"https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/guides/aws-workspace.md"

Error: cannot create mws credentials: MALFORMED_REQUEST: Failed credential validation checks: please use a valid cross account IAM role with permissions setup correctly

do we have any option to overcome this Issue, i am using dependency block for iam policy creation to wait for 3 minutes, but still we are getting same issue

**Comment by nfx** [comment] 2022-06-07 16:11
Please provide configuration and debug logs, as it's completely unclear where the issue is. Most likely it's in invalid configuration.

**Comment by karthik-koantek** [comment] 2022-06-07 16:47
[logs_10.zip](https://github.com/databrickslabs/terraform-provider-databricks/files/8855053/logs_10.zip)

please find attached logs , we are able to resolve InternetGatewayLimitExceeded but unable to resolve 

│Error: cannot create mws credentials: MALFORMED_REQUEST: Failed credential validation checks: please use a valid cross account IAM role with permissions setup correctly

we have tried in multiple regions but getting same error

please find git link: https://github.com/karthik-koantek/databricks-terraform
![image](https://user-images.githubusercontent.com/106896843/172437561-8011ba98-a036-4ec8-aa64-d6ec8651bee9.png)

**Comment by nfx** [comment] 2022-06-07 21:13
Error says that definition of cross account role is wrong. Can you open a support ticket? Closing this issue as it's not related to the provider.

**Closed** 2022-06-07 21:13 UTC
Labels: invalid, cannot reproduce

**Comment by karthik-koantek** [comment] 2022-06-07 23:18
@nfx when we are creating workspace using AWS Qucikstart we are not getting any issues, but when we are trying to run terraform modules then we are seeing above error
