### ISSUE TITLE
[ISSUE] Custom Datatbricks Config file not picked up for provider authentication, when Azure MSI is used

### ISSUE THREAD

**Issue by hungnguyen10897** [databrickslabs/terraform-provider-databricks#397] opened 2020-11-02 08:44 UTC
### Terraform Version
Terraform 0.13.4
Databricks Provider 0.2.7

### Affected Resource(s)
Provider Authentication

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    databricks = {
      source = "databrickslabs/databricks"
      version = "0.2.7"
    }
  }
}

provider "databricks" {
 config_file = "/home/my_user/custom_folder/my-databrickscfg"
}

data "databricks_group" "admins" {
    display_name = "admins"
}

resource "databricks_user" "me" {
  user_name    = "me@example.com"
}

resource "databricks_group_member" "i-am-admin" {
  group_id = data.databricks_group.admins.id
  member_id = databricks_user.me.id
}
```

### Debug Output
```
Error: Authentication is not configured for provider. Please configure it
through one of the following options:
1. DATABRICKS_HOST + DATABRICKS_TOKEN environment variables.
2. host + token provider arguments.
3. azure_databricks_workspace_id + AZ CLI authentication.
4. azure_databricks_workspace_id + azure_client_id + azure_client_secret + azure_tenant_id for Azure Service Principal authentication.
5. Run `databricks configure --token` that will create ~/.databrickscfg file.
```

### Expected Behavior
Provider authenticated

### Actual Behavior
Authentication failed due to "not configured for provider"

### Steps to Reproduce

1. `export DATABRICKS_CONFIG_FILE=<CUSTOM_CONFIG_FILE>`
2. `az login`
3. `token_response=$(az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d)`
4. `export DATABRICKS_AAD_TOKEN=$(jq .accessToken -r <<< "$token_response")`
5. `databricks configure --aad-token`
6. `terrafom init`
7. `terraform plan`

### Further information
According to the documentation, either **config_file** or the **DATABRICKS_CONFIG_FILE** can be used to provide the custom path to the configuration file. Everything works fine if the config file is in the default path (~/.databricks) or the host and token values are used directly inside the provider block.

**Comment by nfx** [comment] 2020-11-02 08:57
@hungnguyen10897 `az login` precedes Databricks CLI config - https://github.com/databrickslabs/terraform-provider-databricks/blob/master/common/client.go#L62 and is meant to be used if no other authorizers were used. 

Why do you need both `az login` and `~/.databrickscfg`? We natively support Azure CLI login.

**Comment by hungnguyen10897** [comment] 2020-11-02 10:16
Hi @nfx, We are running terraform on a VM which is assigned a MSI. Our `az login` is actually run as `az login --identity -u <MSI_ID>`, which logs in to azure as the MSI (Service Principal). If we use the same authentication for databricks provider, it outputs
```
Management API token must be provided for service principal admin user login
(400 on /api/2.0/preview/scim/v2/Groups)
```
I guess it's documented [here](https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/aad/service-prin-aad-token). 

We figure we can bypass this by using the configuration file storing the AAD token. One requirement is that our MSI is the creator of the Databricks workspace, so the Service Principal is listed as *Admin Console/Groups/admins* of the workspace. Somewhat a workaround for this issue #388

Now we need to customize the path to the configuration file. If `az login` precedes Databricks CLI config, I have already tried `az logout` before running `terraform init` and `terraform plan`. Additionally, I have tried this field `azure_use_pat_for_cli = true`

**Comment by nfx** [comment] 2020-11-02 12:05
@hungnguyen10897 please provide more information, including debug logs, as there's not enough context to properly address this issue. You can get filtered debug logs by

```
# or change to apply. Not quite sure how apply will act, though.
TF_LOG=DEBUG terraform plan 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'
```

**Comment by hungnguyen10897** [comment] 2020-11-02 12:46
Here's the debug log

```
2020-11-02T12:34:41.955Z [DEBUG] plugin: starting plugin: path=.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.7/linux_amd64/terraform-provider-databricks_v0.2.7 args=[.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.7/linux_amd64/terraform-provider-databricks_v0.2.7]
path=.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.7/linux_amd64/terraform-provider-databricks_v0.2.7 pid=69256
2020-11-02T12:34:41.956Z [DEBUG] plugin: waiting for RPC address: path=.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.7/linux_amd64/terraform-provider-databricks_v0.2.7
Databricks Terraform Provider (experimental)

Version 0.2.7

https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs

configuring server automatic mTLS: timestamp=2020-11-02T12:34:41.972Z
address=/tmp/plugin347143269 network=unix timestamp=2020-11-02T12:34:42.012Z
path=.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.7/linux_amd64/terraform-provider-databricks_v0.2.7 pid=69256
2020/11/02 12:34:42 [DEBUG] ProviderTransformer: "databricks_group_member.i-am-admin" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/databrickslabs/databricks"]
2020/11/02 12:34:42 [DEBUG] ProviderTransformer: "databricks_user.me" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/databrickslabs/databricks"]
2020/11/02 12:34:42 [DEBUG] ProviderTransformer: "data.databricks_group.admins" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/databrickslabs/databricks"]
2020/11/02 12:34:42 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/databrickslabs/databricks\"]" references: []
2020/11/02 12:34:42 [DEBUG] ReferenceTransformer: "databricks_group_member.i-am-admin" references: [databricks_user.me data.databricks_group.admins]
2020/11/02 12:34:42 [DEBUG] ReferenceTransformer: "databricks_user.me" references: []
2020/11/02 12:34:42 [DEBUG] ReferenceTransformer: "data.databricks_group.admins" references: []
2020-11-02T12:34:42.159Z [DEBUG] plugin: starting plugin: path=.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.7/linux_amd64/terraform-provider-databricks_v0.2.7 args=[.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.7/linux_amd64/terraform-provider-databricks_v0.2.7]
path=.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.7/linux_amd64/terraform-provider-databricks_v0.2.7 pid=69266
2020-11-02T12:34:42.159Z [DEBUG] plugin: waiting for RPC address: path=.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.7/linux_amd64/terraform-provider-databricks_v0.2.7
Databricks Terraform Provider (experimental)

Version 0.2.7

https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs

configuring server automatic mTLS: timestamp=2020-11-02T12:34:42.175Z
address=/tmp/plugin501685615 network=unix timestamp=2020-11-02T12:34:42.216Z
path=.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.7/linux_amd64/terraform-provider-databricks_v0.2.7 pid=69266
2020/11/02 12:34:42 [DEBUG] ProviderTransformer: "data.databricks_group.admins (expand)" (*terraform.nodeExpandRefreshableDataResource) needs provider["registry.terraform.io/databrickslabs/databricks"]
2020/11/02 12:34:42 [DEBUG] ReferenceTransformer: "data.databricks_group.admins (expand)" references: []
2020/11/02 12:34:42 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/databrickslabs/databricks\"]" references: []
2020-11-02T12:34:42.376Z [DEBUG] plugin: starting plugin: path=.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.7/linux_amd64/terraform-provider-databricks_v0.2.7 args=[.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.7/linux_amd64/terraform-provider-databricks_v0.2.7]
path=.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.7/linux_amd64/terraform-provider-databricks_v0.2.7 pid=69275
2020-11-02T12:34:42.377Z [DEBUG] plugin: waiting for RPC address: path=.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.7/linux_amd64/terraform-provider-databricks_v0.2.7
Databricks Terraform Provider (experimental)

Version 0.2.7

https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs

configuring server automatic mTLS: timestamp=2020-11-02T12:34:42.391Z
address=/tmp/plugin389516640 network=unix timestamp=2020-11-02T12:34:42.434Z
2020/11/02 12:34:42 [DEBUG] Resource state not found for node "data.databricks_group.admins", instance data.databricks_group.admins
2020/11/02 12:34:42 [DEBUG] ReferenceTransformer: "data.databricks_group.admins" references: []
data.databricks_group.admins: Refreshing state...
[INFO] ~/.databrickscfg not found on current host
3. azure_databricks_workspace_id + AZ CLI authentication.
4. azure_databricks_workspace_id + azure_client_id + azure_client_secret + azure_tenant_id for Azure Service Principal authentication.
5. Run `databricks configure --token` that will create ~/.databrickscfg file.
Please check https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/index.md#authentication for details
3. azure_databricks_workspace_id + AZ CLI authentication.
4. azure_databricks_workspace_id + azure_client_id + azure_client_secret + azure_tenant_id for Azure Service Principal authentication.
5. Run `databricks configure --token` that will create ~/.databrickscfg file.
Please check https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/index.md#authentication for details
3. azure_databricks_workspace_id + AZ CLI authentication.
4. azure_databricks_workspace_id + azure_client_id + azure_client_secret + azure_tenant_id for Azure Service Principal authentication.
5. Run `databricks configure --token` that will create ~/.databrickscfg file.
Please check https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/index.md#authentication for details
path=.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.7/linux_amd64/terraform-provider-databricks_v0.2.7 pid=69275
```

The provider block:
```
terraform {
  required_providers {
    databricks = {
      source = "databrickslabs/databricks"
      version = "0.2.7"
    }
  }
}

provider "databricks" {
  config_file = "/home/hung/config_folder/.databrickscfg"
}
```

And the environment variable`DATABRICKS_CONFIG_FILE=/home/hung/config_folder/.databrickscfg`. 

Looks like terraform is still looking for the config file in `~/.databrickscfg`

**Comment by nfx** [comment] 2020-11-03 09:04
okay, closing this as duplicate of earlier #388 on proper MSI support. please subscribe to comments on that one.

As always, PRs are more than welcome :)

**Closed by nfx** 2020-11-03 09:04 UTC
