### ISSUE TITLE
[ISSUE] Instance pool constant redeployment

### ISSUE THREAD

**Issue by dzeediscoveryzone** [databrickslabs/terraform-provider-databricks#748] opened 2021-07-27 15:53 UTC
Hi,

We’re running into an odd issue with our Development Account deployment regarding the instance pools. We have terraform modules for our databricks workspaces and all resources inside of them. We have folders for the clusters, instance-pools, cluster policies etc which when you drop json config files inside of them they will deploy/update what is needed.

All of our environments (6 total) have been deployed using this model and 1 account seems to constantly try and redeploy the instance pool, and unfortunately it’s one of our more important ones that Dev uses during the day, so it’s hard to constantly test. What terraform is seeing is that the spot bid price is now null as opposed to 100 and this is forcing the replacement, however this instance is on-demand and the spot price is not null.

I attempted to reproduce this in our QA environment and was unable. I double checked all config files, settings, and anything else that might be different and could not find the root cause. We have also redeployed this instance pool twice now with the same settings and still it is trying to redeploy. I pulled the state file for both Dev and QA and aside from the ID could not spot a difference, see below:

Dev (where the issue resides):
![dev_cluster](https://user-images.githubusercontent.com/88047399/127186043-3b01727f-d6ac-43ed-a340-423c6b5ba4fb.png)

QA (no issue):
![qa_cluster](https://user-images.githubusercontent.com/88047399/127186068-01f80717-0e60-409b-ab9a-128cb9d91a43.png)

Here is the output from terraform plan for the Dev account:
![tf_plan](https://user-images.githubusercontent.com/88047399/127186103-91728997-1fd1-45cb-a7df-c164a1d6388a.png)
 

Is it possible the Dev cluster is holding a reference somewhere in metadata? The only thing different that was done in Dev was that the instance pool was initially spot and then changed to on-demand however I attempted many scenarios in the QA account and could not replicate. Anything you can assist with would be really helpful, thank you!

**Comment by nfx** [comment] 2021-07-27 20:23
@dzeediscoveryzone this looks like an issue on the platform, where GET doesn't return what was in the POST. We'll add another `DiffSuppressFunc`. To immediately solve your issue, please add `ignore_changes` lifecycle https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#ignore_changes

**Comment by dzeediscoveryzone** [comment] 2021-07-27 21:04
@nfx thank you, that did the trick. I added the below to resolve this until the fix is in place:

```terraform
 lifecycle {
    ignore_changes = [aws_attributes["spot_bid_price_percent"], ]
  }

**Comment by nfx** [comment] 2021-07-27 21:55
We probably need to document this on docs, as adding diff suppressions in the codebase may be too risky.

**Comment by roy-work** [comment] 2021-08-20 13:52
You've closed #782 as a duplicate of this one. And … maybe it is? This part concerns me a bit, however:

```
      ~ node_type_id                 = "Standard_D3_v2" -> "Standard_DS3_v2"
```

We looked specifically at that change yesterday, trying to debug this, and what actually got created was a D3_v2, not a DS3_v2. The UI in Azure, I'm also able to create a DS3_v2 specifically, and it shows up differently than what is created by the provider. To me, in that specific case, it looks more like the provider created the wrong class of instance pool?

**Comment by nfx** [comment] 2021-08-21 08:39
@roy-work it looks more of a platform configuration drift error - not returning entities the same as they were created - please open a support ticket and reference this issue.

Sometimes fixing this on platform side is taking longer and we add "special cases" on Terraform plugin side.

**Comment by roy-work** [comment] 2021-08-23 19:27
I'm not sure whether either I am not following, or perhaps I'm not agreeing.

> not returning entities the same as they were created

Yes, I acknowledge that sometimes in Terraform, the exact string as was specified during creation doesn't come back when queried. Normally I'll either ignore these, or adjust the TF to match what Azure is returning, to avoid the drift/difference.

But this,

```
      ~ node_type_id                 = "Standard_D3_v2" -> "Standard_DS3_v2"
```

is not a case of that: the `D3` and `DS3` node types in Databricks, AIUI, are different. Specifically, according to the Azure API,
```
» colordiff -u d3_v2 ds3_v2
--- d3_v2	2021-08-23 15:22:49.000000000 -0400
+++ ds3_v2	2021-08-23 15:22:33.000000000 -0400
@@ -1,19 +1,19 @@
     {
-      "node_type_id": "Standard_D3_v2",
+      "node_type_id": "Standard_DS3_v2",
       "memory_mb": 14336,
       "num_cores": 4,
-      "description": "Standard_D3_v2",
-      "instance_type_id": "Standard_D3_v2",
+      "description": "Standard_DS3_v2",
+      "instance_type_id": "Standard_DS3_v2",
       "is_deprecated": false,
-      "category": "General Purpose (HDD)",
+      "category": "General Purpose",
       "support_ebs_volumes": true,
       "support_cluster_tags": true,
       "num_gpus": 0,
       "node_instance_type": {
-        "instance_type_id": "Standard_D3_v2",
+        "instance_type_id": "Standard_DS3_v2",
         "local_disks": 1,
-        "local_disk_size_gb": 200,
-        "instance_family": "Standard Dv2 Family vCPUs",
+        "local_disk_size_gb": 28,
+        "instance_family": "Standard DSv2 Family vCPUs",
         "local_nvme_disk_size_gb": 0,
         "local_nvme_disks": 0,
         "swap_size": "10g"
@@ -23,8 +23,8 @@
       "display_order": 0,
       "is_io_cache_enabled": false,
       "node_info": {
-        "available_core_quota": 200,
-        "total_core_quota": 200
+        "available_core_quota": 304,
+        "total_core_quota": 400
       },
       "photon_worker_capable": false,
       "photon_driver_capable": false,
```

In the UI, I am able to create both, independently. From my point of view then, asking for a DS3 and getting a D3 appears to be a bug in either the TF provider, or in the Azure API. (But the latter seems less likely, if I am able to create a DS3 in the UI, which I can.)

> please open a support ticket and reference this issue

With TF, or with Azure?

> Terraform's responsibility is to send pool creation request and make sure that it is created the way it's intended. It also reverts any manual changes.

(I agree.)

**Comment by alexott** [comment] 2021-08-24 07:58
@roy-work can you show the declaration of the instance pool? Are you using node_type data source?

**Comment by dzeediscoveryzone** [comment] 2021-09-13 21:48
Hi @nfx - while the fix for my particular issue worked for the time being (adding a lifecycle policy to ignore the spot bid price attribute) it's now affecting us from redeploying the instance pool when changing the spark version. What's happening is that the instance pool change is not instructing terraform to force a redeployment in our dev environment (tested and working in QA where the issue did not exist), which ultimately causes the deployment to fail because the pool already exists, see missing force below:

![image](https://user-images.githubusercontent.com/88047399/133160776-3126a407-28d3-4082-b3d4-3936faaed847.png)

Has there been any progress on the previous issue?

**Comment by alexott** [comment] 2021-09-15 11:17
what terraform version? `preloaded_spark_versions` should be marked with ForceNew

**Comment by dzeediscoveryzone** [comment] 2021-09-15 21:52
@alexott 
> Terraform v0.15.4
on linux_amd64

I believe the issue is that with the temporary fix I have in place for ignoring the aws attribute for spot bid price, it's ignoring the entire instance pool.

**Comment by nfx** [comment] 2021-10-04 12:25
@dzeediscoveryzone Does this issue still occur?

**Comment by dzeediscoveryzone** [comment] 2021-10-05 19:30
> @dzeediscoveryzone Does this issue still occur?

@nfx Yes, it is.
![image](https://user-images.githubusercontent.com/88047399/136090243-f8b34abb-7b3e-445c-a1e7-d74632d31379.png)

**Closed** 2021-10-06 14:37 UTC
Labels: azure, cannot reproduce
