### ISSUE TITLE
[ISSUE] Provider is unable to authenticate

### ISSUE THREAD

**Issue by roy-work** [databrickslabs/terraform-provider-databricks#783] opened 2021-08-18 22:11 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v0.15.5
```
Databricks provider version 0.3.7

### Affected Resource(s)
Please list the resources as a list, for example:
- (the provider, itself)

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Environment variable names
To get relevant environment variable _names_ please copypaste the output of the following command:
`$ env | sort | grep -E 'DATABRICKS|AWS|AZURE|ARM|TEST' | awk -F= '{print $1}'`

### Terraform Configuration Files
```hcl
provider "databricks" {
  azure_workspace_resource_id = azurerm_databricks_workspace.databricks_ws.id
  azure_client_id             = azuread_application.databricks.application_id
  azure_client_secret         = "${random_string.password.result}"
  azure_tenant_id             = "${data.azurerm_client_config.current.tenant_id}"
}
```

### Debug Output
Please add turn on logging, e.g. `TF_LOG=DEBUG terraform apply` and run command again, paste it to gist & provide the link to gist. If you're still willing to paste in log output, make sure you provide only relevant log lines with requests.

It would make it more readable, if you pipe the log through `| grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'`, e.g.:

```
TF_LOG=DEBUG terraform plan 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Should work.

### Actual Behavior
What actually happened? The `plan` fails with,

```
│ Error: authentication is not configured for provider. Please configure it
│ through one of the following options:
│ 1. DATABRICKS_HOST + DATABRICKS_TOKEN environment variables.
│ 2. host + token provider arguments.
│ 3. azure_databricks_workspace_id + AZ CLI authentication.
│ 4. azure_databricks_workspace_id + azure_client_id + azure_client_secret + azure_tenant_id for Azure Service Principal authentication.
│ 5. Run `databricks configure --token` that will create ~/.databrickscfg file.
│ 
│ Please check https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs#authentication for details
```

But we are following step 4. Note, however, that the error uses `azure_databricks_workspace_id`; we pass `azure_workspace_resource_id`. If you follow the link to the docs in the error message above, the attribute referenced in the error message (`azure_databricks_workspace_id`) doesn't appear in the docs; instead, the docs instruct one to use `azure_workspace_resource_id`. <s>I've not had time to test if this is the issue (the code/docs disagree on the name).</s> It seems like the error message is wrong. This code worked in previous versions, so it would be an odd thing (an undeclared breaking change) to change between patch versions.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
Are there anything atypical about your accounts that we should know? We use TFE.

The text `azure_databricks_workspace_id` only appears in the string for this error message, so it would seem that:
1. the error message is wrong
2. there is some other issue that is the cause of the error message

I hit this issue while trying to upgrade our databricks provider from 0.3.2 to 0.3.7. However, that caused TF to also pull in this upgrade:
```
 provider "registry.terraform.io/hashicorp/azurerm" {
-  version     = "2.67.0"
+  version     = "2.72.0"
```
And *that* seems to be the operative change: even if I revert the databricks provider back to 0.3.2, I get this error if I am on the 2.72.0 azurerm, and I don't if I'm on the 2.67.0 azurerm. I did some bisecting, and it seems like it's at 2.71.0 where I get this error. (I don't get it with 2.70.0)

**Comment by alexott** [comment] 2021-08-19 05:53
looks like a dupe of #781

**Comment by nfx** [comment] 2021-08-19 06:42
@roy-work please run TF_LOG=DEBUG terraform apply to enable debug mode through the TF_LOG environment variable. Look specifically for "Explicit and implicit attributes" lines, that should indicate authentication attributes used. Please paste those here

**Comment by roy-work** [comment] 2021-08-19 15:04
> looks like a dupe of #781.

Yes, this does appear to be a dupe of 781.

> Can you try it with 0.3.6 - we'll look into the issue in 0.3.7

See the notes in "Important Factoids"; for me, everything from 0.3.2 to 0.3.7 is broken. (& I simply haven't tested <0.3.2.)
What causes these to break appears to be the `azurerm` version: if I have `azurerm` 2.71.0 or later, I auth fails as described above; if I have ≤2.7.0, then it succeeds.

**Comment by roy-work** [comment] 2021-08-19 15:09
> Explicit and implicit attributes

```
2021-08-19T15:05:25.935Z [INFO]  provider.terraform-provider-databricks_v0.3.6: Explicit and implicit attributes: azure_client_id, azure_client_secret, azure_tenant_id: timestamp=2021-08-19T15:05:25.935Z
```

I am presuming that should include `azure_workspace_resource_id`?

**Comment by nfx** [comment] 2021-08-20 12:38
@roy-work yes, `azure_workspace_resource_id` should not be empty. i'm closing this issue as duplicate in favour of #781 

let's continue discussions there

**Closed by nfx** 2021-08-20 12:38 UTC
