### ISSUE TITLE
[ISSUE] Provider bug

### ISSUE THREAD

**Issue by Paggio** [databrickslabs/terraform-provider-databricks#305] opened 2020-09-08 08:07 UTC
Hi,

I am currently running Terraform v0.13.2.
The output of env | sort | grep -E 'DATABRICKS|AWS|AZURE|ARM|TEST' | awk -F= '{print $1} is empty.

I am writing because I am facing a problem using the databricks provider. 
Basically, even a file main.tf reporting only:

-----------------------------------------------

terraform {
  required_providers {
    databricks = {
      source = "databrickslabs/databricks"
      version = "0.2.4"
    }
  }
}

-----------------------------------------------

Will fail with error, launching the command 'terraform init':

-----------------------------------------------
Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "2.20.0"...
- Finding databrickslabs/databricks versions matching "0.2.4"...
- Installing hashicorp/azurerm v2.20.0...
- Installed hashicorp/azurerm v2.20.0 (signed by HashiCorp)

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
databrickslabs/databricks: no available releases match the given constraints
0.2.4

----------------------------------------------

I am note able to find the provider package, and I really don’t understand why. I am new with Terraform, maybe I am missing something, but I tried with other random packages and everything work fine – this problem comes up only with databricks provider. 
I really don’t know what the problem could be._

**Comment by nfx** [comment] 2020-09-08 08:35
@Paggio it looks like the bug in terraform itself. I was able to reproduce this with 0.13.1 and got it fixed with removing `~/.terraform.d/plugins` directory.

Steps to fix:
* `rm -fr .terraform` to clear downloaded plugins state in your project dir
* `rm -fr ~/.terraform.d/plugins` to clear downloaded plugins state
* `TF_LOG=TRACE terraform init` to reinit your project dir

**Closed** 2020-09-08 08:35 UTC
Labels: bug
