### ISSUE TITLE
[ISSUE] Workspace created by terraform creates storage account which allows public blobs

### ISSUE THREAD

**Issue by favoretti** [databrickslabs/terraform-provider-databricks#194] opened 2020-07-23 12:32 UTC
Hi there,

When DB Workspace is created by terraform (I know the resource isn't in your provider, but maybe you can give us some guidance) there's a storage account that's implicitly created. It has a flag allow_public_blob set to true by default and from what I can see there's no way to influence that. 

Can some knob be exposed so that DB does not create accounts with that setting set to true?

Thanks,
Vlad

**Comment by rk-tbrigley** [comment] 2020-07-23 18:38
some method to access this storage account would be very nice tbh. it is too limited and only accessable by DBFS cli, preventing access with azcopy on cli or azure storage explorer.. this is probalby by design for some reason, but it makes life difficult for users, especially on a standard azure SKU where you cannot mount blob storage.

**Comment by stikkireddy** [comment] 2020-07-23 21:23
Unfortunately that is at the azure workspace level where it is not exposed as that is created via a managed service account. This would require a fundamental change in the Azure Databricks product. Please reach out to your Azure Databricks account team to request for that to be a product feature so it can be considered for the product roadmap. I am closing this issue as this cannot be resolved as a part of this terraform provider project. This is something internal to the product itself and not exposed via any apis.

**Closed by stikkireddy** 2020-07-23 21:23 UTC

**Comment by alex-goncharov** [comment] 2020-07-24 07:52
Thanks for looking at this @stikkireddy.
